### ISSUE TITLE
null cannot be used as parameter value in parameterized tests

### ISSUE THREAD

**Issue by damianw** [Flank/flank#1374]
**Describe the bug**
Using `null` as a parameter value for parameterized tests does not work properly. The exact errors vary - sometimes it appears to get confused about the type of `null`:
```
java.lang.IllegalArgumentException: method com.example.BrokenTest.<init> argument 1 has type java.lang.Integer, got java.lang.String
at java.lang.reflect.Constructor.newInstance(Native Method)
at org.junit.runners.parameterized.BlockJUnit4ClassRunnerWithParameters.createTestUsingConstructorInjection(BlockJUnit4ClassRunnerWithParameters.java:56)
at org.junit.runners.parameterized.BlockJUnit4ClassRunnerWithParameters.createTest(BlockJUnit4ClassRunnerWithParameters.java:46)
at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:260)
...
```

Other times it seems to get very confused about the class name of the test:
```
java.lang.ClassNotFoundException: Invalid name: positions=[0.0])]
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:324)
at androidx.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:72)
at androidx.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:105)
at androidx.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:804)
at androidx.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:575)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:393)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
```

(In this case, `positions=[0.0])` is the tail end of a `toString` for one of the other non-null parameter values.)

**To Reproduce**
The first case can be easily reproduced:
```kotlin
import org.junit.Test
import org.junit.runner.RunWith
import org.junit.runners.Parameterized
import kotlin.test.assertEquals

@RunWith(Parameterized::class)
class BrokenTest(private val testValue: Int?) {

    @Test fun test() {
        if (testValue != null) {
            assertEquals(0, testValue % 2)
        }
    }

    companion object {

        @[JvmStatic Parameterized.Parameters(name = "{0}")]
        fun parameters(): List<Int?> = listOf(null, 0, 2, 4)
    }
}

@RunWith(Parameterized::class)
class WorkingTest(private val testValue: Int?) {

    @Test fun test() {
        if (testValue != null) {
            assertEquals(0, testValue % 2)
        }
    }

    companion object {

        @[JvmStatic Parameterized.Parameters(name = "{0}")]
        fun parameters(): List<Int> = listOf(0, 2, 4)
    }
}
```

I'm not yet 100% sure what causes the second but can investigate a minimal repro sample if needed (especially if that issue appears to be unrelated to the first).

**Expected behavior**
The above tests should all pass, as they do when run locally.

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?

No

> Post the output of ` flank --version`.

20.09.3

**Comment by damianw** [comment]
I did some more investigation and it seems that there may be two separate issues here, although I'm not certain.

The second of the two example stack traces above can be reproduced by using a custom test name - commas in particular appear to be a problem.

A test like the following:
```kotlin
@RunWith(Parameterized::class)
class BrokenTestName2(private val testCase: TestCase) {

    @Test fun test() {
        val expectedRemainder = if (testCase.odd) 1 else 0
        for (value in testCase.values) {
            assertEquals(expectedRemainder, abs(value % 2))
        }
    }

    data class TestCase(
        val values: List<Int>,
        val odd: Boolean,
    )

    companion object {

        @[JvmStatic Parameterized.Parameters(name = "{0}")]
        fun parameters(): List<TestCase> = listOf(
            TestCase(listOf(-4, -2, 0, 2, 4), odd = false),
            TestCase(listOf(-3, -5, -1, 1, 3, 5), odd = true),
        )
    }
}
```

Will produce failures such as:
```
java.lang.ClassNotFoundException: Invalid name:  3
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:324)
at androidx.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:72)
at androidx.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:105)
at androidx.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:804)
at androidx.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:575)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:393)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
```

and similar failures for other values interspersed with commas, e.g. `java.lang.ClassNotFoundException: Invalid name:  -2`, etc.

Such failures appear like this in the FTL UI:

![image](https://user-images.githubusercontent.com/2455337/101087202-bedca680-3566-11eb-918a-c34b123e803d.png)

**Comment by Sloox** [comment]
@damianw Thanks will move it into ranked and work on it asap.

**Comment by piotradamczyk5** [comment]
@damianw could you share config `.yaml` file ?

**Comment by damianw** [comment]
@piotradamczyk5 Would our config still be helpful, or are you all set with the repro cases that you have?

**Comment by piotradamczyk5** [comment]
[20.12.0 with sharding disabled and orchestrator disabled, scenario 1 and 2](https://console.firebase.google.com/u/0/project/flank-open-source/testlab/histories/bh.da0c237aaa33732/matrices/6480221991452424046/executions/bs.51bf0a0831556819/test-cases)

**Comment by bootstraponline** [comment]
Google cloud support recommended opening an issue on the upstream repo for orchestrator. The problem is in orchestrator itself.

I created the issue here:
https://github.com/android/android-test/issues/837
