### ISSUE TITLE
NPE Parsing JUnit XML

### ISSUE THREAD

**Issue by RainNapper** [Flank/flank#1382]
**Describe the bug**
Error is thrown before matrix or storage bucket URLs are printed
Stack trace:
```RunTests
java.lang.NullPointerException
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromString(StdDeserializer.java:267)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1480)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:207)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:197)
        at com.fasterxml.jackson.dataformat.xml.deser.WrapperHandlingDeserializer.deserialize(WrapperHandlingDeserializer.java:118)
        at com.fasterxml.jackson.dataformat.xml.deser.XmlDeserializationContext.readRootValue(XmlDeserializationContext.java:91)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4591)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3546)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3514)
        at ftl.reports.xml.JUnitXmlKt.parseAllSuitesXml(JUnitXml.kt:59)
        at ftl.reports.xml.JUnitXmlKt.parseAllSuitesXml(JUnitXml.kt:51)
        at ftl.gc.GcStorage.downloadJunitXml(GcStorage.kt:120)
        at ftl.args.ArgsHelper.calculateShards(ArgsHelper.kt:250)
        at ftl.run.platform.android.CreateAndroidTestContextKt.calculateShards(CreateAndroidTestContext.kt:55)
        at ftl.run.platform.android.CreateAndroidTestContextKt.access$calculateShards(CreateAndroidTestContext.kt:1)
        at ftl.run.platform.android.CreateAndroidTestContextKt$setupShards$2$invokeSuspend$$inlined$map$lambda$1.invokeSuspend(CreateAndroidTestContext.kt:41)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at ftl.cli.firebase.test.android.AndroidRunCommand.run(AndroidRunCommand.kt:48)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at ftl.Main$Companion$main$1.invoke(Main.kt:59)
        at ftl.Main$Companion$main$1.invoke(Main.kt:49)
        at ftl.run.exception.ExceptionHandlerKt.withGlobalExceptionHandling(ExceptionHandler.kt:11)
        at ftl.Main$Companion.main(Main.kt:55)
        at ftl.Main.main(Main.kt)```
```

**To Reproduce**
> Steps to reproduce the behavior:
Only failing for tablet runs:
```
device:
--
  | - model: Nexus9
  | version: 25
  | locale: en
  | orientation: portrait
```

**Expected behavior**
> A clear and concise description of what you expected to happen.
No crash

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?
>
> Post the output of ` flank --version`.

I'm using a locally built version at this commit: https://github.com/Flank/flank/commit/674ca739419d5e0382abe47327affb3c6394c344

```
version: local_snapshot
--
  | revision: 8cc0786b203e2b3fa9a998a1c30fef244fc2f3c4

```

**Additional context**
> Add any other context about the problem here.
Started happening sometime between 3:30-4:00 PM Dec 7 2020, America/Los_Angeles

**Comment by RainNapper** [comment]
This looks like it's parsing the smart flank xml file. I looked up the file and its contents were:
```
<?xml version='1.0' encoding='UTF-8' ?>
<testsuites/>
```

**Comment by RainNapper** [comment]
So, the tablet suite that we have is fairly small, and I believe it is run in a single matrix.
Since we recently enabled --fail-fast, it seems likely that the matrix hit an error, and we got no results for the entire run, which reflected in the uploaded smart flank XML and then smart flank doesn't handle an empty suite gracefully

**Comment by pawelpasterz** [comment]
I think there are 2 issues
1. NPE which is definitely a bug on the flank side
2. flank is uploading empty results

In the case of 2) I think flank could detect if there are no results fetched from FTL and skip upload.
If I am not wrong, fail fast is used only when an infrastructure error occurred, skipping upload may prevent the previous result from being corrupted

@bootstraponline @RainNapper

**Comment by bootstraponline** [comment]
I agree we should fix the NPE and skip uploading empty results.
