### ISSUE TITLE
Resolve Artifacts Fails on Windows

### ISSUE THREAD

**Issue by Sloox** [Flank/flank#1434]
**Describe the bug**
resolveArtifacts for windows fails due to the failure of privilege's that are required to create a symbolic link.
Files.kt
```
 Exception in thread "main" java.nio.file.FileSystemException:  A required privilege is not held by the client.
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.createSymbolicLink(WindowsFileSystemProvider.java:585)
        at java.nio.file.Files.createSymbolicLink(Files.java:1043)
        at flank.common.FilesKt.createSymbolicLink(Files.kt:17)
```

**To Reproduce**
It was tested on two different windows 10 machines. Windows 10 Home(2004) & Pro(1903).
Both fail. 
Reproduce by running it on Windows 10 native. Not a virtual machine.

**Details (please complete the following information):**
Tested on commit - a7380ff0f3f2a71251593932daefdbbd53291917

Activating developer mode on Windows 10 Pro does not alleviate the problem.
We may need to elevate the privilege's of the java process or investigate a way around this issue.
Ideas.
1. Do an actual File copy for windows instead of a symbolic link
2. Checkout the conditions of this flag `SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE` and which OpenJDK supports this
3. Elevate the user process so it can complete successfully for windows. (Maybe execute a separate bat file or some other way.)

**Comment by Sloox** [comment]
It is possible to bypass the failure by simply copying the files from:
`..\flank\test_artifacts\<unpacked artifacts>`
to 
`..\flank\test_runner\src\test\kotlin\ftl\fixtures\tmp`

**Comment by adamfilipow92** [comment]
I tried to reproduce on win 10 pro native machine and Win 10 pro on parallels but without effect. Did you try run ```resolveArtifacts``` from IntelliJ with admin privileges?
