### ISSUE TITLE
OutOfMemory: Java Heap Size error during tests

### ISSUE THREAD

**Issue by pawelpasterz** [Flank/flank#1577]
From some time flank's CI has been hit with OOM error [example run](https://github.com/Flank/flank/runs/1857957632)
<details>
<summary> Stack trace </summary>

```
ftl.run.TestRunnerTest > mockedIosTestRun local FAILED
    java.lang.OutOfMemoryError: Java heap space
        at (Coroutine boundary.()
        at ftl.run.NewTestRunKt.runTests(NewTestRun.kt:47)
        at ftl.run.NewTestRunKt$newTestRun$2$1.invokeSuspend(NewTestRun.kt:27)
        at ftl.run.NewTestRunKt.cancelTestsOnTimeout(NewTestRun.kt:56)
        at ftl.run.NewTestRunKt$newTestRun$2.invokeSuspend(NewTestRun.kt:27)
        at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:101)
        at ftl.run.TestRunnerTest$mockedIosTestRun local$1.invokeSuspend(TestRunnerTest.kt:135)

        Caused by:
        java.lang.OutOfMemoryError: Java heap space
            at com.google.common.io.ByteStreams.combineBuffers(ByteStreams.java:200)
            at com.google.common.io.ByteStreams.toByteArrayInternal(ByteStreams.java:183)
            at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:221)
            at com.google.cloud.storage.contrib.nio.testing.FakeStorageRpc.create(FakeStorageRpc.java:100)
            at com.google.cloud.storage.StorageImpl$3.call(StorageImpl.java:221)
            at com.google.cloud.storage.StorageImpl$3.call(StorageImpl.java:218)
            at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
            at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
            at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
            at com.google.cloud.storage.StorageImpl.internalCreate(StorageImpl.java:217)
            at com.google.cloud.storage.StorageImpl.create(StorageImpl.java:171)
            at ftl.gc.GcStorage$uploadWithProgress$1.invoke(GcStorage.kt:174)
            at ftl.gc.GcStorage$uploadWithProgress$1.invoke(GcStorage.kt:34)
            at ftl.util.ProgressBarKt.runWithProgress(ProgressBar.kt:39)
            at ftl.util.ProgressBarKt.runWithProgress$default(ProgressBar.kt:34)
            at ftl.gc.GcStorage.uploadWithProgress(GcStorage.kt:172)
            at ftl.gc.GcStorage.access$uploadWithProgress(GcStorage.kt:34)
            at ftl.gc.GcStorage$upload$1.apply(GcStorage.kt:158)
            at ftl.gc.GcStorage$upload$1.apply(GcStorage.kt:34)
            at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
            at ftl.gc.GcStorage.upload$test_runner(GcStorage.kt:148)
            at ftl.gc.GcStorage.upload(GcStorage.kt:63)
            at ftl.util.FileReferenceKt.uploadIfNeeded(FileReference.kt:42)
            at ftl.util.FileReferenceKt.uploadIfNeeded(FileReference.kt:32)
            at ftl.run.platform.ios.CreateXcTestContextKt.createXcTestContexts(CreateXcTestContext.kt:17)
            at ftl.run.platform.ios.CreateIosTestContextKt.createIosTestContexts(CreateIosTestContext.kt:9)
            at ftl.run.platform.RunIosTestsKt$runIosTests$2.invokeSuspend(RunIosTests.kt:49)
            at ftl.run.platform.RunIosTestsKt$runIosTests$2.invoke(RunIosTests.kt)
            at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
            at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:194)
            at ftl.run.platform.RunIosTestsKt.runIosTests(RunIosTests.kt:34)
            at ftl.run.NewTestRunKt.runTests(NewTestRun.kt:47)
```
</details>
After some digging it turned out it's due to `GcStorage` client and `FlankTestRunner`. Here are some of my thoughts and conclusions:

* When `FlankTestRun` is initiated it uploads some artifacts needed during tests. `GcStorage` uses `FakeStorageRpc` (during test run) under the hood and one preserves all artifatcs/files/and other files as String byte[] map. https://github.com/Flank/flank/pull/1350 added two new artifacts that are uploaded and one of them is `EarlGreyExample.zip` which is quite heavy ~47MB.
* There are a couple of tests which uploads those zip file but with different key (which expected). Yet, it leads to the point when we have few big `byte[]` in memory and referenced by `GcStorage` (so gc can not free the memory)
* I checked and the default `xmx` for gradle test task on GH action runner is 512 MB. 
* In general, it is not so small number but...if we run `mockedIosTestRun gcsAndHistoryName` and `mockedIosTestRun local` we already have ~141MB of memory occupied only by those zip files, one for the `FlankTestRunner` and each of tests 'uploads' zip on it's own. And we need to remember there are other lots of other tests that 'uploads' files...
* All above can cause OOM error being thrown (at least I think so)

#### Why I do not see such a problem on my local machine?
TBH -- I'm not sure, maybe GH runner has some additional restrictions for jvm? I ran some tests with increased heap memory for tests and so far I did not encounter OOM error [example run](https://github.com/Flank/flank/pull/1575/checks?check_run_id=1861399645)

#### Solution?
1) easy win is just to increase heap size for the test task (numbers can of course change)
    ```
    tasks.test {
        maxHeapSize = "3072m"
        minHeapSize = "512m"
    }
    ```
2) reimplement our test logic to clean storage after each test, we can leave files 'uploaded' by `FlankTestRunner` or make them uploaded on demand
3) ???

Let me know what do you think and which option should I proceed

**Comment by pawelpasterz** [comment]
I will implement 1) as a temporary solution and create a follow-up issue for solution 2)
