### ISSUE TITLE
Can't upload file to device with other-files feature with gs:// link

### ISSUE THREAD

**Issue by veronikashavrova** [Flank/flank#1971]
**Describe the bug**
Can't upload file to device with  `other-files` feature with gs:// link
Tried only on android

**To Reproduce**
1. Create flank.yml with property 
```
 other-files: 
    /sdcard/eicar.zip: gs://<bucket>/eicar.zip
```
```
Error:
java.nio.file.NoSuchFileException: gs:/<bucket>/eicar.zip
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:421)
	at java.base/java.nio.file.Files.readAllBytes(Files.java:3205)
	at ftl.run.platform.android.UploadOtherFilesKt.upload(UploadOtherFiles.kt:30)
	at ftl.run.platform.android.UploadOtherFilesKt$uploadOtherFiles$2$invokeSuspend$$inlined$map$lambda$1.invokeSuspend(UploadOtherFiles.kt:17)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

This is different from error when file actually doesn't exist:
`'gs://<bucket>/eicarr.zip' from otherFiles doesn't exist`

Apk from same bucket uploaded successfully: 
```
  additional-apks:
    - gs://<bucket>/eicar.apk
```

Same file uploads correctly with absolute path:
```
  other-files: 
    /sdcard/eicar.zip: /Users/<user>/Downloads/eicar.zip
```
With gcloud same file uploaded successfully:
`--other-files /sdcard/eicar.zip=gs://<bucket>/eicar.zip"`

**Expected behavior**
File should be uploaded successfully 

**Details (please complete the following information):**
Using https://github.com/Flank/flank/releases/download/v21.05.0/flank.jar (didn't tried  other versions) 

**Additional context**
As a workaround i'm downloading file via wget to local folder on CI and pass local path to  `other-files`
Using android example from https://flank.github.io/flank/
PS: `other-files` property has incorrect syntax (missing colon) please fix.

**Comment by pawelpasterz** [comment]
Thanks for posting this issue!
Looks like flank is missing one `/` in gs path 🤔 
We will take a look it shortly.
