### ISSUE TITLE
Retry on MixpanelAPI sendData

### ISSUE THREAD

**Issue by AaronMT** [Flank/flank#2141]
Hello,

I'm not familiar with what MixPanel is, but I have a run that hit a 503 today causing a failure post Matrix completion. Can this API call retry in this case?

```Log
[task 2021-08-16T18:57:33.777Z] Matrices webLink
[task 2021-08-16T18:57:33.777Z]   matrix-2vhpi5wc2cyhq https://console.firebase.google.com/project/moz-android-components-230120/testlab/histories/bh.acacddb44ee28c64/matrices/6377018014108605555
[task 2021-08-16T18:57:33.777Z] 
[task 2021-08-16T18:57:37.732Z] java.io.IOException: Server returned HTTP response code: 503 for URL: https://api.mixpanel.com/track?ip=0
[task 2021-08-16T18:57:37.732Z] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
[task 2021-08-16T18:57:37.732Z] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
[task 2021-08-16T18:57:37.732Z] 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
[task 2021-08-16T18:57:37.732Z] 	at com.mixpanel.mixpanelapi.MixpanelAPI.sendData(MixpanelAPI.java:180)
[task 2021-08-16T18:57:37.732Z] 	at com.mixpanel.mixpanelapi.MixpanelAPI.sendMessages(MixpanelAPI.java:203)
[task 2021-08-16T18:57:37.732Z] 	at com.mixpanel.mixpanelapi.MixpanelAPI.deliver(MixpanelAPI.java:121)
[task 2021-08-16T18:57:37.732Z] 	at com.mixpanel.mixpanelapi.MixpanelAPI.deliver(MixpanelAPI.java:101)
[task 2021-08-16T18:57:37.732Z] 	at com.mixpanel.mixpanelapi.MixpanelAPI.sendMessage(MixpanelAPI.java:89)
[task 2021-08-16T18:57:37.732Z] 	at flank.tool.analytics.mixpanel.UsageStatisticsClientKt.send(UsageStatisticsClient.kt:36)
[task 2021-08-16T18:57:37.732Z] 	at flank.tool.analytics.mixpanel.SendConfigurationKt.sendConfiguration(SendConfiguration.kt:17)
[task 2021-08-16T18:57:37.732Z] 	at flank.tool.analytics.mixpanel.SendConfigurationKt.sendConfiguration$default(SendConfiguration.kt:8)
[task 2021-08-16T18:57:37.732Z] 	at flank.tool.analytics.mixpanel.AnalyticsReportKt.send(AnalyticsReport.kt:25)
[task 2021-08-16T18:57:37.732Z] 	at ftl.run.NewTestRunKt$newTestRun$2.invokeSuspend(NewTestRun.kt:50)
```

**Comment by axelzuziak-gogo** [comment]
Mixpanel failure shouldn't crash Flank. 
Flank should silently do one retry and then crash silently.
