### ISSUE TITLE
Custom Sharding iOS Firebase Error

### ISSUE THREAD

**Issue by micai23** [Flank/flank#2490]
Hi I'm trying to implement custom sharding on iOS. Without a custom sharding json file, i'm able to run tests using gihub actions. However with custom sharding I always get this error on github actions.

## Error
```
RunTests
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 2 column 4 path $[0]
	at com.google.gson.Gson.fromJson(Gson.java:1238)
	at com.google.gson.Gson.fromJson(Gson.java:1137)  
```

## Here are my config files

On github actions 
```
    - name: Run Firebase UI Tests using Flank
        id: flank_run
        uses: Flank/flank@master
        with:
          version: v23.10.1
          service_account: ${{ secrets.GOOGLE_CREDENTIALS_DEBUG }}
          platform: ios
          flank_configuration_file: ./scripts/flank-firebase-tests.yml
```

The flank-firebase-tests.yml config file
```
gcloud:
  record-video: true
  timeout: 45m
  async: false
  test: ./Appl-app.zip
  xctestrun-file: ./App-UITests_UITestsPlan_iphoneos17.2-arm64.xctestrun
  device:
    - model: iphone14pro
      version: 16.6
      locale: en
      orientation: portrait
  type: xctest
flank:
  max-test-shards: 1
  shard-time: -1
  disable-sharding: false
  custom-sharding-json: ./scripts/firebase-custom-sharding.json
```

Sharding json file, firebase-custom-sharding.json
```
[
  {
    "EmptyUser1Tests": [
      "EmptyUser/test_01MyCollection_isEmpty", 
      "NowPlayingSuggestionsTest/test_UserCanPlaySuggestedTrack"
    ]
  }
]
```

## Entire error
```
RunTests
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 2 column 4 path $[0]
	at com.google.gson.Gson.fromJson(Gson.java:1238)

	at com.google.gson.Gson.fromJson(Gson.java:1137)
Total run duration: 0m  2s
	- Preparation: 0m 2s
	at com.google.gson.Gson.fromJson(Gson.java:1047)
	at com.google.gson.Gson.fromJson(Gson.java:1014)
	at ftl.ios.xctest.XcTestDataKt.shardsFromV2(XcTestData.kt:186)
	at ftl.ios.xctest.XcTestDataKt.calculateXcTest(XcTestData.kt:43)
	at ftl.ios.xctest.XcTestDataKt.calculateXcTestRunData(XcTestData.kt:32)
	at ftl.args.IosArgs$xcTestRunData$2.invoke(IosArgs.kt:31)
	at ftl.args.IosArgs$xcTestRunData$2.invoke(IosArgs.kt:31)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at ftl.args.IosArgs.getXcTestRunData(IosArgs.kt:31)
	at ftl.run.DumpShardsKt.dumpShards(DumpShards.kt:41)
	at ftl.run.platform.RunIosTestsKt.dumpShardsIfXcTest(RunIosTests.kt:63)
	at ftl.run.platform.RunIosTestsKt.access$dumpShardsIfXcTest(RunIosTests.kt:1)
	at ftl.run.platform.RunIosTestsKt$runIosTests$2.invokeSuspend(RunIosTests.kt:39)
	at ftl.run.platform.RunIosTestsKt$runIosTests$2.invoke(RunIosTests.kt)
	at ftl.run.platform.RunIosTestsKt$runIosTests$2.invoke(RunIosTests.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at ftl.run.platform.RunIosTestsKt.runIosTests(RunIosTests.kt:35)
	at ftl.run.NewTestRunKt.runTests(NewTestRun.kt:54)
	at ftl.run.NewTestRunKt.access$runTests(NewTestRun.kt:1)
	at ftl.run.NewTestRunKt$newTestRun$2$1.invokeSuspend(NewTestRun.kt:30)
	at ftl.run.NewTestRunKt$newTestRun$2$1.invoke(NewTestRun.kt)
	at ftl.run.NewTestRunKt$newTestRun$2$1.invoke(NewTestRun.kt)
	at ftl.run.NewTestRunKt.cancelTestsOnTimeout(NewTestRun.kt:63)
	at ftl.run.NewTestRunKt.cancelTestsOnTimeout$default(NewTestRun.kt:58)
	at ftl.run.NewTestRunKt$newTestRun$2.invokeSuspend(NewTestRun.kt:30)
	at ftl.run.NewTestRunKt$newTestRun$2.invoke(NewTestRun.kt)
	at ftl.run.NewTestRunKt$newTestRun$2.invoke(NewTestRun.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:89)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:151)
	at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:107)
	at ftl.run.NewTestRunKt.newTestRun(NewTestRun.kt:26)
	at ftl.domain.RunTestIosKt$invoke$2$1.invokeSuspend(RunTestIos.kt:57)
	at ftl.domain.RunTestIosKt$invoke$2$1.invoke(RunTestIos.kt)
	at ftl.domain.RunTestIosKt$invoke$2$1.invoke(RunTestIos.kt)
	at ftl.presentation.RunStateKt$runBlockingWithObservingRunState$1.invokeSuspend(RunState.kt:21)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at ftl.presentation.RunStateKt.runBlockingWithObservingRunState(RunState.kt:17)
	at ftl.domain.RunTestIosKt.invoke(RunTestIos.kt:55)
	at ftl.presentation.cli.firebase.test.ios.IosRunCommand.run(IosRunCommand.kt:58)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2[170](https://github.com/tidal-engineering/iOS/actions/runs/8688799463/job/23825207058#step:47:175))
	at ftl.Main$main$1.invoke(Main.kt:12)
	at ftl.Main$main$1.invoke(Main.kt:10)
	at ftl.run.exception.ExceptionHandlerKt.withGlobalExceptionHandling(ExceptionHandler.kt:24)
	at ftl.run.exception.ExceptionHandlerKt.withGlobalExceptionHandling(ExceptionHandler.kt:14)
	at ftl.Main.main(Main.kt:10)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 2 column 4 path $[0]
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:358)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:[171](https://github.com/tidal-engineering/iOS/actions/runs/8688799463/job/23825207058#step:47:176))
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:144)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	... 61 more
Error: Process completed with exit code
```

**Comment by ypenn21** [comment]
The sharding feature is lacking currently. According to this blog.. https://sahil-insights.medium.com/real-device-testing-xcuitest-firebase-test-lab-github-actions-1cb5f07f4ba6 . However for android instrumentation it is available.
