### ISSUE TITLE
Flakes attribute never set correctly in FullJunitReport.xml

### ISSUE THREAD

**Issue by AaronMT** [Flank/flank#2504]
```XML
<testsuite name="Pixel2.arm-30-en_US-portrait" tests="462" failures="1" flakes="0" errors="0" skipped="0" time="10277.484" timestamp="2024-06-23T06:02:53" hostname="localhost">
    <testcase name="verifyButtonTest" classname="org.app.verifyButtonTestTest" time="0.222" flaky="true">
     ...
</testsuite>
```
Shouldn't `flakes` attribute be `1` in this case? This is with `v23.10.1`.

Our Flank config specifies `num-flaky-test-attempts: 1` with `full-junit-result: true` under the `Flank` section.

**Comment by SelaseKay** [comment]
Hi @AaronMT , thanks for the report. I'm unable to reproduce this issue. Are you still experiencing this? Also, do you pass a value to `use-orchestrator` or you stick to the default(`true`)?

**Comment by SelaseKay** [comment]
Hi @AaronMT , I was able to reproduce this once but for some weird reason, I'm not able to reproduce it anymore. Are you still experiencing this issue?

**Comment by AaronMT** [comment]
Yes, I still see this issue on `23.10.1`. Here's an example report from our CI.

https://firefoxci.taskcluster-artifacts.net/d8K2VuK9SuKeZDYVpkTvBw/0/public/results/FullJUnitReport.xml

```xml
<testcase name="verifyReaderModeControlsTest" classname="org.mozilla.fenix.ui.ReaderViewTest" time="0.275" flaky="true">
<failure>
java.security.ProviderException: Keystore operation failed at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:331) at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:612) at mozilla.components.lib.dataprotect.KeyStoreWrapper.makeKeyFor(Keystore.kt:106) at mozilla.components.lib.dataprotect.Keystore.generateKey(Keystore.kt:195) at mozilla.components.lib.dataprotect.Keystore.<init>(Keystore.kt:162) at mozilla.components.lib.dataprotect.Keystore.<init>(Keystore.kt:155) at mozilla.components.lib.dataprotect.SecurePreferencesImpl23$keystore$2.invoke(SecureAbove22Preferences.kt:158) at mozilla.components.lib.dataprotect.SecurePreferencesImpl23$keystore$2.invoke(SecureAbove22Preferences.kt:158) at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) at mozilla.components.lib.dataprotect.SecurePreferencesImpl23.getKeystore(SecureAbove22Preferences.kt:158) at mozilla.components.lib.dataprotect.SecurePreferencesImpl23.generateManagedKeyIfNecessary(SecureAbove22Preferences.kt:227) at mozilla.components.lib.dataprotect.SecurePreferencesImpl23.getString(SecureAbove22Preferences.kt:187) at mozilla.components.lib.dataprotect.SecureAbove22Preferences.getString(SecureAbove22Preferences.kt:76) at mozilla.components.service.sync.logins.LoginsCrypto.getStoredKey(LoginsCrypto.kt:53) at mozilla.components.concept.storage.KeyManager.getManagedKey(KeyManager.kt:65) at mozilla.components.concept.storage.KeyManager.getOrGenerateKey$suspendImpl(KeyManager.kt:52) at mozilla.components.concept.storage.KeyManager.getOrGenerateKey(Unknown Source:0) at mozilla.components.service.sync.logins.SyncableLoginsStorage$list$2.invokeSuspend(SyncableLoginsStorage.kt:159) at mozilla.components.service.sync.logins.SyncableLoginsStorage$list$2.invoke(Unknown Source:8) at mozilla.components.service.sync.logins.SyncableLoginsStorage$list$2.invoke(Unknown Source:4) at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:61) at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163) at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1) at mozilla.components.service.sync.logins.SyncableLoginsStorage.list(SyncableLoginsStorage.kt:158) at org.mozilla.fenix.FenixApplication$setAutofillMetrics$1.invokeSuspend(FenixApplication.kt:989) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104) at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111) at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99) at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702) Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@72a02ef, Dispatchers.IO] Caused by: android.security.KeyStoreException: 16 at android.security.KeyStore.getKeyStoreException(KeyStore.java:1289) ... 33 more
</failure>
<webLink>
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5010455154038943430/executions/bs.ca8a668d2750f889/testcases/3
</webLink>
</testcase>
```

Where `flaky` is set to `true`, but the top level `flakes` is set to `0`

**Comment by SelaseKay** [comment]
Are you able to reproduce this locally?

**Comment by SelaseKay** [comment]
Can you provide a sample app and test apk?

**Comment by AaronMT** [comment]
As Flank (via Test Lab) generates these artifacts, I'm not sure what you mean by reproducing locally.

Here's a recent (`arm64v8a` debug build from our CI) and no-arch test APK

https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/M4IjtgpLTWuZaUg43Q0ByA/artifacts/public/build/target.arm64-v8a.apk

https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/TvdzLJF3Tiij13O8gqe9dA/artifacts/public/build/target.noarch.apk

**Comment by SelaseKay** [comment]
I apologise for the confusion. By reproducing locally, I meant executing Flank on your own machine to initiate Test Lab runs, rather than in CI.

**Comment by SelaseKay** [comment]
Kindly provide the device specifications you have in your flank.yml

**Comment by SelaseKay** [comment]
Seems to work fine locally:

```
<?xml version='1.0' encoding='UTF-8' ?>
<testsuites>
  <testsuite name="Pixel2.arm-30-en_US-portrait" tests="45" failures="11" flakes="1" errors="0" skipped="0" time="575.163" timestamp="2024-10-17T20:08:37" hostname="localhost">
    <testcase name="testExperimentUnenrolledViaSecretMenu" classname="org.mozilla.fenix.experimentintegration.GenericExperimentIntegrationTest" time="50.552">
      <failure>androidx.test.espresso.NoActivityResumedException: No activities in stage RESUMED. Did you forget to launch the activity. (test.getActivity() or similar)?
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
      ......
    </testcase>
    <testcase name="settingsTest" classname="org.mozilla.fenix.screenshots.ComposeMenuScreenShotTest" time="10.278" flaky="true">
      <failure>FAILED
    </failure>
......
    </testcase>
  </testsuite>
</testsuites>

```

**Comment by AaronMT** [comment]
```
gcloud:
  results-bucket: ...
  record-video: true
  timeout: 15m
  async: false
  num-flaky-test-attempts: 1

  app: /app/path
  test: /test/path

  auto-google-login: false
  use-orchestrator: true
  environment-variables:
    clearPackageData: true
  performance-metrics: true

  test-targets:
    - notPackage org.mozilla.fenix.screenshots
    - notPackage org.mozilla.fenix.syncintegration
    - notPackage org.mozilla.fenix.experimentintegration

  device:
    - model: Pixel2.arm
      version: 30
      locale: en_US

flank:
  project: ...
  max-test-shards: 100
  num-test-runs: 1
  output-style: compact
  full-junit-result: true
  ```
  
  Does this have anything to do with `full-junit-result`?

**Comment by SelaseKay** [comment]
Do you experience this issue when you run flank in your local environment with the above configuration?

**Comment by AaronMT** [comment]
Hello again, yes I was able to reproduce with a local Flank run call to the same configuration above.

**Comment by SelaseKay** [comment]
Hi @AaronMT, after some investigation, I've found that the issue is related to the `max-test-shards` property. If you either omit this property or set it to zero, the behavior is as expected (with `flakes` reflecting the correct value).

**Comment by AaronMT** [comment]
Thanks for investigating. Out of curiosity are you planning a new release?
