### ISSUE TITLE
NullPointerException on windows while fetching artifacts

### ISSUE THREAD

**Issue by jakob-grabner** [Flank/flank#628]
I get a NullPointerException while fetching artifacts after the test run completed. I guess it is a Windows issue since it works just fine on linux.

```
FetchArtifacts
  ..............................
  Updating matrix file

java.lang.NullPointerException
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:247)
	at java.nio.file.Paths.get(Paths.java:84)
	at ftl.reports.util.ReportManager.getWebLink(ReportManager.kt:44)
	at ftl.reports.util.ReportManager.processXml(ReportManager.kt:68)
	at ftl.reports.util.ReportManager.parseTestSuite(ReportManager.kt:89)
	at ftl.reports.util.ReportManager.generate(ReportManager.kt:95)
	at ftl.run.TestRunner.newRun(TestRunner.kt:349)
	at ftl.run.TestRunner$newRun$1.invokeSuspend(TestRunner.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.ResumeModeKt.resumeUninterceptedMode(ResumeMode.kt:45)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterCompletionInternal(Scopes.kt:32)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:310)
	at kotlinx.coroutines.JobSupport.tryFinalizeFinishingState(JobSupport.kt:236)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:849)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:811)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:787)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at ftl.cli.firebase.test.android.AndroidRunCommand.run(AndroidRunCommand.kt:49)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1729)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2101)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2068)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1935)
	at picocli.CommandLine.execute(CommandLine.java:1864)
	at ftl.Main$Companion.main(Main.kt:41)
	at ftl.Main.main(Main.kt)

```

**Comment by bootstraponline** [comment]
Yeah, that looks like a Windows bug. I'll look into it.

**Comment by ynsok** [comment]
The same, any idea how to solve it ?

**Comment by pawelpasterz** [comment]
Hey @ynsok @jakob-grabner 
Recently we introduced new way of creating results (based on TL api, not fetched xml) Could you verified if this approach solved your issue? Please, use snapshot version https://github.com/Flank/flank/releases/tag/flank_snapshot
Let me know

**Comment by bootstraponline** [comment]
I think the way to test this issue would be to run flank in a windows VM.

**Comment by Sloox** [comment]
I have a physical windows device will look into this problem

**Comment by Sloox** [comment]
Due to current work on supporting windows. This error has not been observed on both Windows with and without WSL2. 
The original error message contained a NPE based on pathing. 
Windows Pathing fixes were applied here:
https://github.com/Flank/flank/pull/1114
This ticket will remain open until the larger ticket is closed.

**Comment by bootstraponline** [comment]
I'm closing the ticket since I think this issue is fixed. If you see the issue again, please let us know!
