### ISSUE TITLE
Getting delete permission exception when using results-dir option

### ISSUE THREAD

**Issue by prolificcoder** [Flank/flank#790]
I am trying enable code-coverage and seeing this error `java.lang.RuntimeException: com.google.cloud.storage.StorageException: firebase-test-lab@sofi-test.iam.gserviceaccount.com` does not have storage.objects.delete access to cloud-test-sofi-test/coverage_ec/app-debug-androidTest.apk. Does the service account need higher permissions? wondering why delete is needed though (edited) 

I also tried with orchestrator, that didn't change anything. 

My flank output looks like this 

```
AndroidArgs
     gcloud:
       results-bucket: cloud-test-sofi-test
       results-dir: null
       record-video: true
       timeout: 15m
       async: false
       results-history-name: null
       # Android gcloud
       app: /builds/sofiinc/mobile/wealth-android/app/build/outputs/apk/debug/app-debug.apk
       test: /builds/sofiinc/mobile/wealth-android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
       auto-google-login: true
       use-orchestrator: false
       directories-to-pull:
         - /sdcard/
       performance-metrics: false
       test-runner-class: null
       test-targets:
         - package com.sofi.mobile.tests.money
         -  notAnnotation com.sofi.mobile.Quarantine
       device:
         - model: Nexus5X
           version: 26
           locale: en
           orientation: portrait
       num-flaky-test-attempts: 1
     flank:
       max-test-shards: -1
       shard-time: -1
       num-test-runs: 1
       smart-flank-gcs-path: 
       smart-flank-disable-upload: false
       files-to-download:
         - .*/sdcard/[^/]+\.ec$
       test-targets-always-run:
       disable-sharding: false
       project: sofi-test
       local-result-dir: ../app/build/test-results/money-tests/
       # Android Flank Yml
       keep-file-path: false
       additional-app-test-apks:
```

Stacktrace:
```
RunTests
   Uploading app-debug-androidTest.apk .  Uploading app-debug.apk .
 java.lang.RuntimeException: com.google.cloud.storage.StorageException: firebase-test-lab@sofi-test.iam.gserviceaccount.com does not have storage.objects.delete access to cloud-test-sofi-test/coverage_ec/app-debug-androidTest.apk.
 	at ftl.gc.GcStorage.upload(GcStorage.kt:144)
 	at ftl.gc.GcStorage.upload(GcStorage.kt:50)
 	at ftl.run.AndroidTestRunner$resolveApks$2$invokeSuspend$$inlined$forEach$lambda$2.invokeSuspend(AndroidTestRunner.kt:77)
 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
 	Suppressed: java.lang.RuntimeException: com.google.cloud.storage.StorageException: firebase-test-lab@sofi-test.iam.gserviceaccount.com does not have storage.objects.delete access to cloud-test-sofi-test/coverage_ec/app-debug.apk.
 		at ftl.gc.GcStorage.upload(GcStorage.kt:144)
 		at ftl.gc.GcStorage.upload(GcStorage.kt:50)
 		at ftl.run.AndroidTestRunner$resolveApks$2$invokeSuspend$$inlined$forEach$lambda$1.invokeSuspend(AndroidTestRunner.kt:76)
 		... 5 more
 	Caused by: com.google.cloud.storage.StorageException: firebase-test-lab@sofi-test.iam.gserviceaccount.com does not have storage.objects.delete access to cloud-test-sofi-test/coverage_ec/app-debug.apk.
```

**Comment by bootstraponline** [comment]
The action item for the Flank team is to identify what in the codebase is requiring the delete permissions.

> Caused by: com.google.cloud.storage.StorageException: firebase-test-lab@sofi-test.iam.gserviceaccount.com does not have storage.objects.delete access to cloud-test-sofi-test/coverage_ec/app-debug.apk.

**Comment by pawelpasterz** [comment]
Hey @prolificcoder , please verify with latest flank version. I see you are using older version, flank is using google api client and it might be that client might be old. If error still occurs in latest flank release it will be easier for us to investigate :) Thanks!

cc 
@bootstraponline

**Comment by prolificcoder** [comment]
@Pasterzp I upgraded to latest flank and I still see the error. I think its trying to delete the debug and debug-test apk's. I removed all code coverage aspects from it but still seeing the error. here is the full output

```
 AndroidArgs
     gcloud:
       results-bucket: cloud-test-sofi-test
       results-dir: coverage_ec
       record-video: true
       timeout: 15m
       async: false
       results-history-name: null
       # Android gcloud
       app: /builds/sofiinc/mobile/wealth-android/app/build/outputs/apk/debug/app-debug.apk
       test: /builds/sofiinc/mobile/wealth-android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
       auto-google-login: true
       use-orchestrator: true
       directories-to-pull:
         - /sdcard/
       performance-metrics: false
       test-runner-class: null
       test-targets:
         - package com.sofi.mobile.tests.money
         -  notAnnotation com.sofi.mobile.Quarantine
       device:
         - model: Nexus5X
           version: 26
           locale: en
           orientation: portrait
       num-flaky-test-attempts: 1
     flank:
       max-test-shards: -1
       shard-time: -1
       num-test-runs: 1
       smart-flank-gcs-path: 
       smart-flank-disable-upload: false
       files-to-download:
         - .*/sdcard/[^/]+\.ec$
       test-targets-always-run:
       disable-sharding: false
       project: sofi-test
       local-result-dir: ../app/build/test-results/money-tests/
       # Android Flank Yml
       keep-file-path: false
       additional-app-test-apks:
 RunTests
   Uploading app-debug-androidTest.apk .  Uploading app-debug.apk .
 java.lang.RuntimeException: com.google.cloud.storage.StorageException: firebase-test-lab@sofi-test.iam.gserviceaccount.com does not have storage.objects.delete access to cloud-test-sofi-test/coverage_ec/app-debug-androidTest.apk.
 	at ftl.gc.GcStorage.upload(GcStorage.kt:144)
 	at ftl.gc.GcStorage.upload(GcStorage.kt:50)
 	at ftl.run.AndroidTestRunner$resolveApks$2$invokeSuspend$$inlined$forEach$lambda$2.invokeSuspend(AndroidTestRunner.kt:77)
 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
 	Suppressed: java.lang.RuntimeException: com.google.cloud.storage.StorageException: firebase-test-lab@sofi-test.iam.gserviceaccount.com does not have storage.objects.delete access to cloud-test-sofi-test/coverage_ec/app-debug.apk.
 		at ftl.gc.GcStorage.upload(GcStorage.kt:144)
 		at ftl.gc.GcStorage.upload(GcStorage.kt:50)
 		at ftl.run.AndroidTestRunner$resolveApks$2$invokeSuspend$$inlined$forEach$lambda$1.invokeSuspend(AndroidTestRunner.kt:76)
 		... 5 more
 	Caused by: com.google.cloud.storage.StorageException: firebase-test-lab@sofi-test.iam.gserviceaccount.com does not have storage.objects.delete access to cloud-test-sofi-test/coverage_ec/app-debug.apk.
 		at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:229)
 		at com.google.cloud.storage.spi.v1.HttpStorageRpc.create(HttpStorageRpc.java:310)
 		at com.google.cloud.storage.StorageImpl$3.call(StorageImpl.java:196)
 		at com.google.cloud.storage.StorageImpl$3.call(StorageImpl.java:193)
 		at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
 		at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
 		at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
 		at com.google.cloud.storage.StorageImpl.internalCreate(StorageImpl.java:192)
 		at com.google.cloud.storage.StorageImpl.create(StorageImpl.java:154)
 		at ftl.gc.GcStorage.upload(GcStorage.kt:110)
 		... 7 more
 	Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
 {
   "code" : 403,
   "errors" : [ {
     "domain" : "global",
     "message" : "firebase-test-lab@sofi-test.iam.gserviceaccount.com does not have storage.objects.delete access to cloud-test-sofi-test/coverage_ec/app-debug.apk.",
     "reason" : "forbidden"
   } ],
   "message" : "firebase-test-lab@sofi-test.iam.gserviceaccount.com does not have storage.objects.delete access to cloud-test-sofi-test/coverage_ec/app-debug.apk."
 }
 		at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
 		at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
 		at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
 		at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:554)
 		at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:474)
 		at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:591)
 		at com.google.cloud.storage.spi.v1.HttpStorageRpc.create(HttpStorageRpc.java:307)
 		... 15 more
 Caused by: com.google.cloud.storage.StorageException: firebase-test-lab@sofi-test.iam.gserviceaccount.com does not have storage.objects.delete access to cloud-test-sofi-test/coverage_ec/app-debug-androidTest.apk.
 	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:229)
 	at com.google.cloud.storage.spi.v1.HttpStorageRpc.create(HttpStorageRpc.java:310)
 	at com.google.cloud.storage.StorageImpl$3.call(StorageImpl.java:196)
 	at com.google.cloud.storage.StorageImpl$3.call(StorageImpl.java:193)
 	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
 	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
 	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
 	at com.google.cloud.storage.StorageImpl.internalCreate(StorageImpl.java:192)
 	at com.google.cloud.storage.StorageImpl.create(StorageImpl.java:154)
 	at ftl.gc.GcStorage.upload(GcStorage.kt:110)
 	... 7 more
 Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
 {
   "code" : 403,
   "errors" : [ {
     "domain" : "global",
     "message" : "firebase-test-lab@sofi-test.iam.gserviceaccount.com does not have storage.objects.delete access to cloud-test-sofi-test/coverage_ec/app-debug-androidTest.apk.",
     "reason" : "forbidden"
   } ],
   "message" : "firebase-test-lab@sofi-test.iam.gserviceaccount.com does not have storage.objects.delete access to cloud-test-sofi-test/coverage_ec/app-debug-androidTest.apk."
 }
```

and here is how my flank.yml looks like

```
gcloud:
   results-bucket: cloud-test-sofi-test
   record-video: true
   app: ../app/build/outputs/apk/debug/app-debug.apk
   test: ../app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
   use-orchestrator: false
   environment-variables:
    endpoint: https://testendponit.com/
   performance-metrics: false
   num-flaky-test-attempts: 1
   device:
   - model: Nexus5X
     version: 26
     locale: en
     orientation: portrait
flank:
   local-result-dir: ../app/build/test-results/ui-tests/
```

**Comment by bootstraponline** [comment]
I think flank might delete the apks on Google cloud storage if they already exist, to ensure we aren't running stale apks.

**Comment by prolificcoder** [comment]
this is something new because older flank 8.1.0 isn't doesn't need that. Do I need to request higher permissions for the service account or would it possible to check if you have delete permission before deleting files?

**Comment by bootstraponline** [comment]
seems like a potential bug in flank, I don't think flank should require delete permissions.

The team is a bit backlogged right now, we will look into this soon.

**Comment by pawelpasterz** [comment]
Service account does not have `storage.objects.delete` by default
![Screenshot 2020-06-23 at 18 38 48](https://user-images.githubusercontent.com/32893017/86429152-f5c83b00-bcee-11ea-958b-020d8bf3fcee.png)

Flank's logic is rather simple and depends fully on Google storage client
```
...
val fileBlob = BlobInfo.newBuilder(rootGcsBucket, validGcsPath).build()
storage.create(fileBlob, fileBytes)
...
```
(`storage` object is created is created from credentials)
My guess is, under the hood client checks if the same file in the bucket and remove it if there is (before upload).
I am not sure if there is something we can improve on flank's side when it comes to permissions...

>this is something new because older flank 8.1.0 isn't doesn't need that. Do I need to request higher permissions for the service account or would it possible to check if you have delete permission before deleting files?

There were some issues with uploading multiple apks in 8.1.0 version and, IMO, those bugs were actually a 'feature' that might enable you to do so :) (but that's mu guess)
I'll look how `gcloud` behaves and get back with more info. 
You can also verify it on your side, please run
`gcloud firebase test android run your-congif.yml:gcloud`

**Comment by pawelpasterz** [comment]
https://cloud.google.com/sdk/gcloud/reference/firebase/test/android/run#--results-dir
According to google docs `--results-dir` is recommended to be unique for each run. 

> Caution: if specified, this argument must be unique for each test matrix you create, otherwise results from multiple test matrices will be overwritten or intermingled.

As I understand, there is deletion action performed in case of same apk names.

Flank creates uniq `results-dir` if none specified (or `null` like it is stated in first logs you pasted).
https://cloud.google.com/storage/docs/access-control/iam-permissions
> Note: In order to overwrite existing objects, both storage.objects.create and storage.objects.delete permissions are required.

I tried to reproduce this error but failed so far

**Comment by bootstraponline** [comment]
recommendation is to add delete permission if you're seeing this error message.
