### ISSUE TITLE
Exception thrown while updating matrix file

### ISSUE THREAD

**Issue by francescocervone** [Flank/flank#827]
**Describe the bug**
An exception was launched while updating matrix file
```
Updating matrix file

java.lang.IllegalStateException: testCase.startTime must not be null
	at ftl.reports.api.PrepareForJUnitResultKt$$special$$inlined$sortedBy$2.compare(Comparisons.kt:321)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1438)
	at kotlin.collections.ArraysKt___ArraysJvmKt.sortWith(_ArraysJvm.kt:1959)
	at kotlin.collections.CollectionsKt___CollectionsKt.sortedWith(_Collections.kt:986)
	at ftl.reports.api.PrepareForJUnitResultKt.reduceTestCases(PrepareForJUnitResult.kt:101)
	at ftl.reports.api.PrepareForJUnitResultKt.reduceTestCases(PrepareForJUnitResult.kt:24)
	at ftl.reports.api.PrepareForJUnitResultKt.prepareForJUnitResult(PrepareForJUnitResult.kt:12)
	at ftl.reports.api.CreateJUnitTestResultKt.createJUnitTestResult(CreateJUnitTestResult.kt:9)
	at ftl.reports.api.ProcessFromApiKt.processXmlFromApi(ProcessFromApi.kt:22)
	at ftl.reports.util.ReportManager.parseTestSuite(ReportManager.kt:95)
	at ftl.reports.util.ReportManager.generate(ReportManager.kt:101)
	at ftl.run.NewTestRunKt$newTestRun$2.invokeSuspend(NewTestRun.kt:26)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.ResumeModeKt.resumeUninterceptedMode(ResumeMode.kt:45)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterCompletionInternal(Scopes.kt:32)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:310)
	at kotlinx.coroutines.JobSupport.tryFinalizeFinishingState(JobSupport.kt:236)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:849)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:811)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:787)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at ftl.cli.firebase.test.android.AndroidRunCommand.run(AndroidRunCommand.kt:54)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
	at picocli.CommandLine.execute(CommandLine.java:1904)
	at ftl.Main$Companion$main$1.invoke(Main.kt:53)
	at ftl.Main$Companion$main$1.invoke(Main.kt:43)
	at ftl.util.Utils.withGlobalExceptionHandling(Utils.kt:132)
	at ftl.Main$Companion.main(Main.kt:49)
	at ftl.Main.main(Main.kt)

```

**To Reproduce**
It happened just once. I'm not able to reproduce it.

**Expected behavior**
Matrix should be updated without launching any exception

**Details:**
Flank version 20.05.1

**Additional context**
This is our configuration (I obfuscated some private info):
```yaml
gcloud:
  results-bucket: test-lab-[mybucket]
  results-dir: null
  record-video: false
  timeout: 30m
  async: false
  client-details:
  network-profile: null
  results-history-name: null
  app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
  test: /code/app/build/outputs/apk/androidTest/staging/debug/app-staging-debug-androidTest.apk
  additional-apks:
  auto-google-login: false
  use-orchestrator: true
  directories-to-pull:
  other-files:
  performance-metrics: false
  num-uniform-shards: null
  test-runner-class: null
  test-targets:
  robo-directives:
  robo-script: null
  device:
    - model: NexusLowRes
      version: 28
      locale: it
      orientation: portrait
  num-flaky-test-attempts: 3

flank:
  max-test-shards: 10
  shard-time: 120
  num-test-runs: 1
  smart-flank-gcs-path: gs://[myproject].appspot.com/flank/all-instrumented-tests.xml
  smart-flank-disable-upload: false
  files-to-download:
  test-targets-always-run:
  disable-sharding: false
  project: [myproject]
  local-result-dir: results
  keep-file-path: false
  additional-app-test-apks:
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/1/build/outputs/apk/androidTest/debug/1-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/2/build/outputs/apk/androidTest/debug/2-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/3/build/outputs/apk/androidTest/debug/3-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/4/build/outputs/apk/androidTest/debug/4-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/5/build/outputs/apk/androidTest/debug/5-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/6/build/outputs/apk/androidTest/debug/6-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/7/build/outputs/apk/androidTest/debug/7-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/8/build/outputs/apk/androidTest/debug/8-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/9/build/outputs/apk/androidTest/debug/9-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/10/build/outputs/apk/androidTest/debug/10-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/11/build/outputs/apk/androidTest/debug/11-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/12/build/outputs/apk/androidTest/debug/12-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/13/build/outputs/apk/androidTest/debug/13-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/14/build/outputs/apk/androidTest/debug/14-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/15/build/outputs/apk/androidTest/debug/15-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/16/build/outputs/apk/androidTest/debug/16-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/17/build/outputs/apk/androidTest/debug/17-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/18/build/outputs/apk/androidTest/debug/18-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/19/build/outputs/apk/androidTest/debug/19-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/20/build/outputs/apk/androidTest/debug/20-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/21/build/outputs/apk/androidTest/debug/21-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/22/build/outputs/apk/androidTest/debug/22-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/23/build/outputs/apk/androidTest/release/23-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/24/build/outputs/apk/androidTest/debug/24-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/25/build/outputs/apk/androidTest/debug/25-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/26/build/outputs/apk/androidTest/debug/26-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/27/build/outputs/apk/androidTest/debug/27-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/28/build/outputs/apk/androidTest/debug/28-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/29/build/outputs/apk/androidTest/debug/29-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/30/build/outputs/apk/androidTest/debug/30-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/31/build/outputs/apk/androidTest/debug/31-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/32/build/outputs/apk/androidTest/debug/32-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/33/build/outputs/apk/androidTest/debug/33-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/34/build/outputs/apk/androidTest/debug/34-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/35/build/outputs/apk/androidTest/debug/35-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/36/build/outputs/apk/androidTest/debug/36-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/37/build/outputs/apk/androidTest/debug/37-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/38/build/outputs/apk/androidTest/debug/38-debug-androidTest.apk
    - app: /code/app/build/outputs/apk/staging/debug/app-staging-debug.apk
      test: /code/39/build/outputs/apk/androidTest/debug/39-debug-androidTest.apk
  run-timeout: -1
  legacy-junit-result: false
  ignore-failed-tests: false
```

**Comment by pawelpasterz** [comment]
Hey @francescocervone thanks for posting issue.
This bug was fixed with #798 (currently in snapshot version) and will be available with next release.
