### ISSUE TITLE
IllegalStateException: toolResultsStep must not be null

### ISSUE THREAD

**Issue by jrodbx** [Flank/flank#870]
I'm using Fladle 0.10.1 which depends on Flank 20.05.2.

When I add the following to my fladle block:
```
fladle {
  ...
  directoriesToPull = [
      "/data/data/com.squareup.cash.beta.debug/test-attachments"
  ]
```

I get the following error:
```
RunTests

  Smart Flank cache hit: 0% (0 / 3)
  Shard times: 360s

  Uploading app-internal-debug-androidTest.apk .  Uploading app-internal-debug.apk .
  ...

FetchArtifacts
  
java.lang.IllegalStateException: toolResultsStep must not be null
	at ftl.reports.api.CreateTestExecutionDataKt.createTestExecutionData(CreateTestExecutionData.kt:31)
	at ftl.reports.api.CreateTestExecutionDataKt$createTestExecutionDataListAsync$1$1$1.invokeSuspend(CreateTestExecutionData.kt:22)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

**Comment by pawelpasterz** [comment]
@jrodbx 
Thanks for reporting this issue, looks like another `null` issue on java - kotlin connection...

> When I add the following to my fladle block:

fladle {
  ...
  directoriesToPull = [
      "/data/data/com.squareup.cash.beta.debug/test-attachments"
  ]

Can you confirm it is happening only when you add `directoriesToPull` option? (and happens all the time)

**Comment by jrodbx** [comment]
Correct.  Without `directoriesToPull`, builds pass.  With it, they always fail with the same error.

**Comment by pawelpasterz** [comment]
Interesting, looks like FTL can't handle directories with `.` inside names...anyway, thanks for the input!

**Comment by piotradamczyk5** [comment]
The problem is that paths must start with `/sdcard` or `/data/local/tmp` [link](https://cloud.google.com/sdk/gcloud/reference/firebase/test/android/run#--directories-to-pull).
However I am adding validation to flank with these instruction in case of failure and also filter `null toolResultsStep`
