### ISSUE TITLE
Non-deterministic issue when parsing JUnitReport.xml generated by Flank 20.06.2

### ISSUE THREAD

**Issue by plnice** [Flank/flank#872]
**Describe the bug**

After updating from Flank 8.0.1 to 20.06.2 and switching to server-side sharding sometimes on our CI (TeamCity) we see following error when parsing `JUnitReport.xml`:
```
[17:00:00]Ant JUnit report watcher
[17:00:00][Ant JUnit report watcher] 1 report found for paths:
[17:00:00][Ant JUnit report watcher] results/**/JUnitReport.xml
[17:00:00][Ant JUnit report watcher] Parsing errors
[17:00:00][Parsing errors] Failed to parse 1 report
[17:00:00][Parsing errors] results/2020-06-25_16-47-33.675000_QnCW/JUnitReport.xml: Content is not allowed in prolog.
[17:00:00][Parsing errors] jetbrains.buildServer.util.XmlXppAbstractParser$3: Content is not allowed in prolog.
	at jetbrains.buildServer.util.XmlXppAbstractParser.parse(XmlXppAbstractParser.java:39)
	at jetbrains.buildServer.util.XmlXppAbstractParser.parse(XmlXppAbstractParser.java:31)
	at jetbrains.buildServer.xmlReportPlugin.parsers.antJUnit.AntJUnitReportParser.parse(AntJUnitReportParser.java:179)
	at jetbrains.buildServer.xmlReportPlugin.ParseReportCommand.run(ParseReportCommand.java:62)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at jetbrains.buildServer.util.XmlXppAbstractParser.parseWithSAX(XmlXppAbstractParser.java:240)
	at jetbrains.buildServer.util.XmlXppAbstractParser.parse(XmlXppAbstractParser.java:37)
	... 8 more
```
The issue is non-deterministic, in most cases the report gets parsed, but this never happened to us when using Flank 8. Did anyone already run into the problem? Any ideas what could be a cause? The XML files look correct for me, I compared two files from failed and successful runs, the difference is only in reported time of running tests, both files do not contain BOM marker (checked using vim).

**To Reproduce**

1. Run tests using Flank and then try to parse the report using TeamCity's report parsing feature.

**Expected behavior**

No error raised by TeamCity when parsing the `JUnitReport.xml`.

**Details (please complete the following information):**

Flank 20.06.2

**Additional context**

\-

**Comment by piotradamczyk5** [comment]
Asked @plnice on private slack message for sample failing report

**Comment by piotradamczyk5** [comment]
sample failing raport
```
<?xml version='1.0' encoding='UTF-8' ?>
<testsuites>
  <testsuite name="Pixel2-27-en-portrait" tests="2" failures="0" flakes="0" errors="0" skipped="0" time="39.151" timestamp="2020-07-01T16:46:41" hostname="localhost">
    <testcase name="loginSuccessBetaEnvTest" classname="com.miquido.play360.login.LoginBetaEnvTest" time="19.133"/>
    <testcase name="testPaymentsCard" classname="com.miquido.play360.dashboard.PaymentCardBetaEnvTest" time="20.019"/>
  </testsuite>
</testsuites>
```

**Comment by piotradamczyk5** [comment]
Raising issue to TeamCity https://youtrack.jetbrains.com/issue/TW-66753

**Comment by piotradamczyk5** [comment]
The issue could not be reproduced after doing the following steps:
- Validate XML
- Clear XML buffer unnecessary characters
- Checking hex code of the provided report
- Compare reading report with using Kotlin file loading
- Checking git history
- Ask user about TeamCity configuration 

All research is described in [file](https://github.com/Flank/flank/blob/master/docs/bugs/872_error_when_parsing_Junit_raport_using_TeamCityCI.md)

Currently, the issue was [reported to TeamCity](https://youtrack.jetbrains.com/issue/TW-66753), they also cannot reproduce this bug.

This task is closed now and will be reopened if there will be new circumstances
